name: Gemmini CI
on: [push]
jobs:
  install-esp-toolchain:
    name: install-esp-toolchain
    runs-on: ubuntu-latest
    container:
      image: ucbbar/chipyard-ci-image:554b436
      options: --entrypoint /bin/bash
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: generate-keys
        id: genkey
        run: |
          echo "::set-output name=install-esp-toolchain-cache-key::extra-tests-${{ github.ref }}-${{ github.sha }}"
      - name: cache
        uses: actions/cache@v2
        with:
          path: /home/riscvuser/esp-tools-install
          key: ${{ steps.genkey.outputs.install-esp-toolchain-cache-key }}
          restore-keys: ${{ steps.genkey.outputs.install-esp-toolchain-cache-key }}
      - name: toolchain-build
        run: .github/scripts/build-toolchains.sh esp-tools
