name: Gemmini CI
on: [push]
jobs:
  install-esp-toolchain:
    name: install-esp-toolchain
    runs-on: ubuntu-latest
    container:
      image: ucbbar/chipyard-ci-image:554b436
      options: --entrypoint /bin/bash
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: toolchain-build
        run: .github/scripts/build-toolchains.sh esp-tools

  prepare-build-environment:
    name: prepare-build-environment
    runs-on: ubuntu-latest
    container:
      image: ucbbar/chipyard-ci-image:554b436
      options: --entrypoint /bin/bash
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup build environment
        run: .github/scripts/prepare-for-rtl-build.sh
      - name: install verilator
        run: .github/scripts/install-verilator.sh

  prepare-gemmini-config:
    name: prepare-gemmini-config
    runs-on: ubuntu-latest
    needs: [prepare-build-environment, install-esp-toolchain]
    container:
      image: ucbbar/chipyard-ci-image:554b436
      options: --entrypoint /bin/bash
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: create hash
        run: .github/scripts/create-hash.sh
      - name: Building Gemmini Config using Verilator
        run: .github/scripts/do-rtl-build.sh

  spike-run-tests:
    name: spike-run-tests
    runs-on: ubuntu-latest
    needs: prepare-gemmini-config
    container:
      image: ucbbar/chipyard-ci-image:554b436
      options: --entrypoint /bin/bash
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: run-tests
        run: ./github/scripts/run-tests-spike.sh

  rtl-run-tests:
    name: rtl-run-tests
    runs-on: ubuntu-latest
    needs: prepare-gemmini-config
    container:
      image: ucbbar/chipyard-ci-image:554b436
      options: --entrypoint /bin/bash
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: run-tests
        run: ./github/scripts/run-tests-rtl.sh
